//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplar
    {
        public int k_id { get; set; }
        public string k_ad { get; set; }
        public Nullable<int> k_kategori { get; set; }
        public string k_yazar { get; set; }
        public string k_durum { get; set; }
        public byte[] k_resim { get; set; }
        public string k_ozet { get; set; }
        public Nullable<int> k_sayfa { get; set; }
    
        public virtual kategori kategori { get; set; }
    }
}
