//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicig
    {
        public int K_id { get; set; }
        public string K_kadı { get; set; }
        public string K_kparola { get; set; }
        public string K_Adsoyad { get; set; }
        public string K_Telefon { get; set; }
    }
}
